apiVersion: v1
kind: Service
metadata:
  name: cloudknowledges
  labels: 
    apps: cloudknowledges
spec:
  selector:
    app: cloudknowledges
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
